# Generated by Django 3.1 on 2020-12-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('ToDoCount', models.IntegerField(verbose_name='Durum')),
                ('text', models.CharField(max_length=150, verbose_name='Yazı')),
                ('photo', models.CharField(max_length=200, verbose_name='Fotoğraf')),
            ],
        ),
    ]
