# Generated by Django 3.1 on 2021-01-19 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Uygulama', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblist',
            name='ToDoCount',
        ),
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Todostext', models.CharField(max_length=300, verbose_name='Yazı')),
                ('TodosJob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Uygulama.joblist')),
            ],
        ),
    ]
