# Generated by Django 3.1 on 2021-01-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uygulama', '0003_auto_20210119_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblist',
            name='GerceklesenSure',
            field=models.CharField(blank=True, default=0, max_length=500, verbose_name='Gerçekleşen Süre'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='IsAciklamasi',
            field=models.CharField(blank=True, default=0, max_length=500, verbose_name='İş Açıklaması'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='KartNo',
            field=models.CharField(blank=True, default=0, max_length=500, verbose_name='Kart No'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='Notlar',
            field=models.CharField(blank=True, default=0, max_length=500, verbose_name='Notlar'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='ProjeNo',
            field=models.CharField(blank=True, default=0, max_length=500, verbose_name='Proje No'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='TahminiSure',
            field=models.CharField(blank=True, default=0, max_length=500, verbose_name='Tahmini Süre'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='Tarih',
            field=models.CharField(blank=True, default=0, max_length=500, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='TeknikUzman',
            field=models.CharField(blank=True, default=0, max_length=500, verbose_name='Teknik Uzman'),
        ),
        migrations.AlterField(
            model_name='todos',
            name='todoAciklama',
            field=models.CharField(blank=True, default=0, max_length=500, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='todos',
            name='todoDurum',
            field=models.CharField(blank=True, default=0, max_length=500, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='todos',
            name='todoTarih',
            field=models.CharField(blank=True, default=0, max_length=500, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='todos',
            name='todoYapilacakIs',
            field=models.CharField(blank=True, default=0, max_length=500, verbose_name='Yapılacak İş'),
        ),
    ]
