# Generated by Django 3.1 on 2021-01-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uygulama', '0006_auto_20210120_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todos',
            name='todoname',
        ),
        migrations.AddField(
            model_name='todos',
            name='a',
            field=models.CharField(blank=True, default=0, max_length=2, verbose_name='t'),
        ),
        migrations.AddField(
            model_name='todos',
            name='d',
            field=models.CharField(blank=True, default=0, max_length=2, verbose_name='t'),
        ),
        migrations.AddField(
            model_name='todos',
            name='t',
            field=models.CharField(blank=True, default=0, max_length=2, verbose_name='t'),
        ),
        migrations.AddField(
            model_name='todos',
            name='y',
            field=models.CharField(blank=True, default=0, max_length=2, verbose_name='t'),
        ),
    ]
